// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cecu_push_driving_app_info.proto
// Protobuf Java Version: 4.30.2

package com.desaysv.psmap.model.bean;

public final class CecuPushDrivingAppInfo {
    private CecuPushDrivingAppInfo() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 30,
                /* patch= */ 2,
                /* suffix= */ "",
                CecuPushDrivingAppInfo.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code com.desaysv.psmap.model.bean.EnumModState}
     */
    public enum EnumModState
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>MOD_OFF = 0;</code>
         */
        MOD_OFF(0),
        /**
         * <code>MOD_NOT_READY = 1;</code>
         */
        MOD_NOT_READY(1),
        /**
         * <code>MOD_READY = 2;</code>
         */
        MOD_READY(2),
        /**
         * <code>MOD_LOCATION = 3;</code>
         */
        MOD_LOCATION(3),
        /**
         * <code>MOD_STANDBY = 4;</code>
         */
        MOD_STANDBY(4),
        /**
         * <code>MOD_WAIT = 5;</code>
         */
        MOD_WAIT(5),
        /**
         * <code>MOD_ACTIVE = 6;</code>
         */
        MOD_ACTIVE(6),
        /**
         * <code>MOD_BGLOCATION = 7;</code>
         */
        MOD_BGLOCATION(7),
        /**
         * <code>MOD_BGSTANDBY = 8;</code>
         */
        MOD_BGSTANDBY(8),
        /**
         * <code>MOD_BGWAIT = 9;</code>
         */
        MOD_BGWAIT(9),
        /**
         * <code>MOD_D130_WAIT = 10;</code>
         */
        MOD_D130_WAIT(10),
        /**
         * <code>MOD_ERROR = 11;</code>
         */
        MOD_ERROR(11),
        UNRECOGNIZED(-1),
        ;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EnumModState.class.getName());
        }

        /**
         * <code>MOD_OFF = 0;</code>
         */
        public static final int MOD_OFF_VALUE = 0;
        /**
         * <code>MOD_NOT_READY = 1;</code>
         */
        public static final int MOD_NOT_READY_VALUE = 1;
        /**
         * <code>MOD_READY = 2;</code>
         */
        public static final int MOD_READY_VALUE = 2;
        /**
         * <code>MOD_LOCATION = 3;</code>
         */
        public static final int MOD_LOCATION_VALUE = 3;
        /**
         * <code>MOD_STANDBY = 4;</code>
         */
        public static final int MOD_STANDBY_VALUE = 4;
        /**
         * <code>MOD_WAIT = 5;</code>
         */
        public static final int MOD_WAIT_VALUE = 5;
        /**
         * <code>MOD_ACTIVE = 6;</code>
         */
        public static final int MOD_ACTIVE_VALUE = 6;
        /**
         * <code>MOD_BGLOCATION = 7;</code>
         */
        public static final int MOD_BGLOCATION_VALUE = 7;
        /**
         * <code>MOD_BGSTANDBY = 8;</code>
         */
        public static final int MOD_BGSTANDBY_VALUE = 8;
        /**
         * <code>MOD_BGWAIT = 9;</code>
         */
        public static final int MOD_BGWAIT_VALUE = 9;
        /**
         * <code>MOD_D130_WAIT = 10;</code>
         */
        public static final int MOD_D130_WAIT_VALUE = 10;
        /**
         * <code>MOD_ERROR = 11;</code>
         */
        public static final int MOD_ERROR_VALUE = 11;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static EnumModState valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static EnumModState forNumber(int value) {
            switch (value) {
                case 0:
                    return MOD_OFF;
                case 1:
                    return MOD_NOT_READY;
                case 2:
                    return MOD_READY;
                case 3:
                    return MOD_LOCATION;
                case 4:
                    return MOD_STANDBY;
                case 5:
                    return MOD_WAIT;
                case 6:
                    return MOD_ACTIVE;
                case 7:
                    return MOD_BGLOCATION;
                case 8:
                    return MOD_BGSTANDBY;
                case 9:
                    return MOD_BGWAIT;
                case 10:
                    return MOD_D130_WAIT;
                case 11:
                    return MOD_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<EnumModState>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                EnumModState> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<EnumModState>() {
                    public EnumModState findValueByNumber(int number) {
                        return EnumModState.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.getDescriptor().getEnumTypes().get(0);
        }

        private static final EnumModState[] VALUES = values();

        public static EnumModState valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private EnumModState(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.desaysv.psmap.model.bean.EnumModState)
    }

    /**
     * Protobuf enum {@code com.desaysv.psmap.model.bean.EnumModMapperState}
     */
    public enum EnumModMapperState
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>MOD_MAPPER_OFF = 0;</code>
         */
        MOD_MAPPER_OFF(0),
        /**
         * <code>MOD_MAPPER_NOT_READY = 1;</code>
         */
        MOD_MAPPER_NOT_READY(1),
        /**
         * <code>MOD_MAPPER_READY = 2;</code>
         */
        MOD_MAPPER_READY(2),
        /**
         * <code>MOD_MAPPER_MAP_TRAINING = 3;</code>
         */
        MOD_MAPPER_MAP_TRAINING(3),
        /**
         * <code>MOD_MAPPER_MAP_SAVING = 4;</code>
         */
        MOD_MAPPER_MAP_SAVING(4),
        /**
         * <code>MOD_MAPPER_FINISH = 5;</code>
         */
        MOD_MAPPER_FINISH(5),
        /**
         * <code>MOD_MAPPER_ERROR = 6;</code>
         */
        MOD_MAPPER_ERROR(6),
        UNRECOGNIZED(-1),
        ;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EnumModMapperState.class.getName());
        }

        /**
         * <code>MOD_MAPPER_OFF = 0;</code>
         */
        public static final int MOD_MAPPER_OFF_VALUE = 0;
        /**
         * <code>MOD_MAPPER_NOT_READY = 1;</code>
         */
        public static final int MOD_MAPPER_NOT_READY_VALUE = 1;
        /**
         * <code>MOD_MAPPER_READY = 2;</code>
         */
        public static final int MOD_MAPPER_READY_VALUE = 2;
        /**
         * <code>MOD_MAPPER_MAP_TRAINING = 3;</code>
         */
        public static final int MOD_MAPPER_MAP_TRAINING_VALUE = 3;
        /**
         * <code>MOD_MAPPER_MAP_SAVING = 4;</code>
         */
        public static final int MOD_MAPPER_MAP_SAVING_VALUE = 4;
        /**
         * <code>MOD_MAPPER_FINISH = 5;</code>
         */
        public static final int MOD_MAPPER_FINISH_VALUE = 5;
        /**
         * <code>MOD_MAPPER_ERROR = 6;</code>
         */
        public static final int MOD_MAPPER_ERROR_VALUE = 6;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static EnumModMapperState valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static EnumModMapperState forNumber(int value) {
            switch (value) {
                case 0:
                    return MOD_MAPPER_OFF;
                case 1:
                    return MOD_MAPPER_NOT_READY;
                case 2:
                    return MOD_MAPPER_READY;
                case 3:
                    return MOD_MAPPER_MAP_TRAINING;
                case 4:
                    return MOD_MAPPER_MAP_SAVING;
                case 5:
                    return MOD_MAPPER_FINISH;
                case 6:
                    return MOD_MAPPER_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<EnumModMapperState>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                EnumModMapperState> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<EnumModMapperState>() {
                    public EnumModMapperState findValueByNumber(int number) {
                        return EnumModMapperState.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.getDescriptor().getEnumTypes().get(1);
        }

        private static final EnumModMapperState[] VALUES = values();

        public static EnumModMapperState valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private EnumModMapperState(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.desaysv.psmap.model.bean.EnumModMapperState)
    }

    /**
     * Protobuf enum {@code com.desaysv.psmap.model.bean.EnumNohdState}
     */
    public enum EnumNohdState
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>NOHD_OFF = 0;</code>
         */
        NOHD_OFF(0),
        /**
         * <code>NOHD_STANDBY = 1;</code>
         */
        NOHD_STANDBY(1),
        /**
         * <code>NOHD_READY = 2;</code>
         */
        NOHD_READY(2),
        /**
         * <code>NOHD_ACTIVE = 3;</code>
         */
        NOHD_ACTIVE(3),
        /**
         * <code>NOHD_ERROR = 4;</code>
         */
        NOHD_ERROR(4),
        UNRECOGNIZED(-1),
        ;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EnumNohdState.class.getName());
        }

        /**
         * <code>NOHD_OFF = 0;</code>
         */
        public static final int NOHD_OFF_VALUE = 0;
        /**
         * <code>NOHD_STANDBY = 1;</code>
         */
        public static final int NOHD_STANDBY_VALUE = 1;
        /**
         * <code>NOHD_READY = 2;</code>
         */
        public static final int NOHD_READY_VALUE = 2;
        /**
         * <code>NOHD_ACTIVE = 3;</code>
         */
        public static final int NOHD_ACTIVE_VALUE = 3;
        /**
         * <code>NOHD_ERROR = 4;</code>
         */
        public static final int NOHD_ERROR_VALUE = 4;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static EnumNohdState valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static EnumNohdState forNumber(int value) {
            switch (value) {
                case 0:
                    return NOHD_OFF;
                case 1:
                    return NOHD_STANDBY;
                case 2:
                    return NOHD_READY;
                case 3:
                    return NOHD_ACTIVE;
                case 4:
                    return NOHD_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<EnumNohdState>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                EnumNohdState> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<EnumNohdState>() {
                    public EnumNohdState findValueByNumber(int number) {
                        return EnumNohdState.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.getDescriptor().getEnumTypes().get(2);
        }

        private static final EnumNohdState[] VALUES = values();

        public static EnumNohdState valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private EnumNohdState(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.desaysv.psmap.model.bean.EnumNohdState)
    }

    /**
     * Protobuf enum {@code com.desaysv.psmap.model.bean.EnumNocdState}
     */
    public enum EnumNocdState
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>NOCD_OFF = 0;</code>
         */
        NOCD_OFF(0),
        /**
         * <code>NOCD_STANDBY = 1;</code>
         */
        NOCD_STANDBY(1),
        /**
         * <code>NOCD_READY = 2;</code>
         */
        NOCD_READY(2),
        /**
         * <code>NOCD_ACTIVE = 3;</code>
         */
        NOCD_ACTIVE(3),
        /**
         * <code>NOCD_ERROR = 4;</code>
         */
        NOCD_ERROR(4),
        UNRECOGNIZED(-1),
        ;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    EnumNocdState.class.getName());
        }

        /**
         * <code>NOCD_OFF = 0;</code>
         */
        public static final int NOCD_OFF_VALUE = 0;
        /**
         * <code>NOCD_STANDBY = 1;</code>
         */
        public static final int NOCD_STANDBY_VALUE = 1;
        /**
         * <code>NOCD_READY = 2;</code>
         */
        public static final int NOCD_READY_VALUE = 2;
        /**
         * <code>NOCD_ACTIVE = 3;</code>
         */
        public static final int NOCD_ACTIVE_VALUE = 3;
        /**
         * <code>NOCD_ERROR = 4;</code>
         */
        public static final int NOCD_ERROR_VALUE = 4;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static EnumNocdState valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static EnumNocdState forNumber(int value) {
            switch (value) {
                case 0:
                    return NOCD_OFF;
                case 1:
                    return NOCD_STANDBY;
                case 2:
                    return NOCD_READY;
                case 3:
                    return NOCD_ACTIVE;
                case 4:
                    return NOCD_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<EnumNocdState>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                EnumNocdState> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<EnumNocdState>() {
                    public EnumNocdState findValueByNumber(int number) {
                        return EnumNocdState.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.getDescriptor().getEnumTypes().get(3);
        }

        private static final EnumNocdState[] VALUES = values();

        public static EnumNocdState valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private EnumNocdState(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.desaysv.psmap.model.bean.EnumNocdState)
    }

    public interface CECUPushDrivingAppInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * MOD行车状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
         *
         * @return The enum numeric value on the wire for modState.
         */
        int getModStateValue();

        /**
         * <pre>
         * MOD行车状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
         *
         * @return The modState.
         */
        com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState getModState();

        /**
         * <pre>
         * MOD建图状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
         *
         * @return The enum numeric value on the wire for modMappingState.
         */
        int getModMappingStateValue();

        /**
         * <pre>
         * MOD建图状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
         *
         * @return The modMappingState.
         */
        com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState getModMappingState();

        /**
         * <pre>
         * NOHD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
         *
         * @return The enum numeric value on the wire for nohdState.
         */
        int getNohdStateValue();

        /**
         * <pre>
         * NOHD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
         *
         * @return The nohdState.
         */
        com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState getNohdState();

        /**
         * <pre>
         * NOCD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
         *
         * @return The enum numeric value on the wire for nocdState.
         */
        int getNocdStateValue();

        /**
         * <pre>
         * NOCD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
         *
         * @return The nocdState.
         */
        com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState getNocdState();

        /**
         * <pre>
         * 自推荐地图id
         * </pre>
         *
         * <code>uint32 mod_recommend_map_id = 5;</code>
         *
         * @return The modRecommendMapId.
         */
        int getModRecommendMapId();

        /**
         * <pre>
         * 用户选择地图id
         * </pre>
         *
         * <code>uint32 mod_user_select_map_id = 6;</code>
         *
         * @return The modUserSelectMapId.
         */
        int getModUserSelectMapId();

        /**
         * <pre>
         * 建图完成地图id
         * </pre>
         *
         * <code>uint32 mod_mapper_map_id = 7;</code>
         *
         * @return The modMapperMapId.
         */
        int getModMapperMapId();

        /**
         * <pre>
         * 开始/结束发送导航实时数据
         * </pre>
         *
         * <code>bool send_real_time_msg = 8;</code>
         *
         * @return The sendRealTimeMsg.
         */
        boolean getSendRealTimeMsg();

        /**
         * <pre>
         * 重新发送导航规划路径
         * </pre>
         *
         * <code>bool resend_navi_global_route = 9;</code>
         *
         * @return The resendNaviGlobalRoute.
         */
        boolean getResendNaviGlobalRoute();
    }

    /**
     * <pre>
     * *
     * 概述：域控行车（MOD/NOHD）应用信息（域控提供给导航App）
     * 类型：Push
     * Sender_ID:
     * RSP_Type:
     * Msg_Set:
     * Msg_ID：
     * Direction：cECU --&gt; App（OEM导航App）
     * </pre>
     * <p>
     * Protobuf type {@code com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo}
     */
    public static final class CECUPushDrivingAppInfo extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo)
            CECUPushDrivingAppInfoOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 30,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    CECUPushDrivingAppInfo.class.getName());
        }

        // Use CECUPushDrivingAppInfo.newBuilder() to construct.
        private CECUPushDrivingAppInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private CECUPushDrivingAppInfo() {
            modState_ = 0;
            modMappingState_ = 0;
            nohdState_ = 0;
            nocdState_ = 0;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo.class, com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo.Builder.class);
        }

        public static final int MOD_STATE_FIELD_NUMBER = 1;
        private int modState_ = 0;

        /**
         * <pre>
         * MOD行车状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
         *
         * @return The enum numeric value on the wire for modState.
         */
        @Override
        public int getModStateValue() {
            return modState_;
        }

        /**
         * <pre>
         * MOD行车状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
         *
         * @return The modState.
         */
        @Override
        public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState getModState() {
            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.forNumber(modState_);
            return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.UNRECOGNIZED : result;
        }

        public static final int MOD_MAPPING_STATE_FIELD_NUMBER = 2;
        private int modMappingState_ = 0;

        /**
         * <pre>
         * MOD建图状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
         *
         * @return The enum numeric value on the wire for modMappingState.
         */
        @Override
        public int getModMappingStateValue() {
            return modMappingState_;
        }

        /**
         * <pre>
         * MOD建图状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
         *
         * @return The modMappingState.
         */
        @Override
        public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState getModMappingState() {
            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.forNumber(modMappingState_);
            return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.UNRECOGNIZED : result;
        }

        public static final int NOHD_STATE_FIELD_NUMBER = 3;
        private int nohdState_ = 0;

        /**
         * <pre>
         * NOHD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
         *
         * @return The enum numeric value on the wire for nohdState.
         */
        @Override
        public int getNohdStateValue() {
            return nohdState_;
        }

        /**
         * <pre>
         * NOHD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
         *
         * @return The nohdState.
         */
        @Override
        public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState getNohdState() {
            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.forNumber(nohdState_);
            return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.UNRECOGNIZED : result;
        }

        public static final int NOCD_STATE_FIELD_NUMBER = 4;
        private int nocdState_ = 0;

        /**
         * <pre>
         * NOCD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
         *
         * @return The enum numeric value on the wire for nocdState.
         */
        @Override
        public int getNocdStateValue() {
            return nocdState_;
        }

        /**
         * <pre>
         * NOCD状态机
         * </pre>
         *
         * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
         *
         * @return The nocdState.
         */
        @Override
        public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState getNocdState() {
            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.forNumber(nocdState_);
            return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.UNRECOGNIZED : result;
        }

        public static final int MOD_RECOMMEND_MAP_ID_FIELD_NUMBER = 5;
        private int modRecommendMapId_ = 0;

        /**
         * <pre>
         * 自推荐地图id
         * </pre>
         *
         * <code>uint32 mod_recommend_map_id = 5;</code>
         *
         * @return The modRecommendMapId.
         */
        @Override
        public int getModRecommendMapId() {
            return modRecommendMapId_;
        }

        public static final int MOD_USER_SELECT_MAP_ID_FIELD_NUMBER = 6;
        private int modUserSelectMapId_ = 0;

        /**
         * <pre>
         * 用户选择地图id
         * </pre>
         *
         * <code>uint32 mod_user_select_map_id = 6;</code>
         *
         * @return The modUserSelectMapId.
         */
        @Override
        public int getModUserSelectMapId() {
            return modUserSelectMapId_;
        }

        public static final int MOD_MAPPER_MAP_ID_FIELD_NUMBER = 7;
        private int modMapperMapId_ = 0;

        /**
         * <pre>
         * 建图完成地图id
         * </pre>
         *
         * <code>uint32 mod_mapper_map_id = 7;</code>
         *
         * @return The modMapperMapId.
         */
        @Override
        public int getModMapperMapId() {
            return modMapperMapId_;
        }

        public static final int SEND_REAL_TIME_MSG_FIELD_NUMBER = 8;
        private boolean sendRealTimeMsg_ = false;

        /**
         * <pre>
         * 开始/结束发送导航实时数据
         * </pre>
         *
         * <code>bool send_real_time_msg = 8;</code>
         *
         * @return The sendRealTimeMsg.
         */
        @Override
        public boolean getSendRealTimeMsg() {
            return sendRealTimeMsg_;
        }

        public static final int RESEND_NAVI_GLOBAL_ROUTE_FIELD_NUMBER = 9;
        private boolean resendNaviGlobalRoute_ = false;

        /**
         * <pre>
         * 重新发送导航规划路径
         * </pre>
         *
         * <code>bool resend_navi_global_route = 9;</code>
         *
         * @return The resendNaviGlobalRoute.
         */
        @Override
        public boolean getResendNaviGlobalRoute() {
            return resendNaviGlobalRoute_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (modState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.MOD_OFF.getNumber()) {
                output.writeEnum(1, modState_);
            }
            if (modMappingState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.MOD_MAPPER_OFF.getNumber()) {
                output.writeEnum(2, modMappingState_);
            }
            if (nohdState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.NOHD_OFF.getNumber()) {
                output.writeEnum(3, nohdState_);
            }
            if (nocdState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.NOCD_OFF.getNumber()) {
                output.writeEnum(4, nocdState_);
            }
            if (modRecommendMapId_ != 0) {
                output.writeUInt32(5, modRecommendMapId_);
            }
            if (modUserSelectMapId_ != 0) {
                output.writeUInt32(6, modUserSelectMapId_);
            }
            if (modMapperMapId_ != 0) {
                output.writeUInt32(7, modMapperMapId_);
            }
            if (sendRealTimeMsg_ != false) {
                output.writeBool(8, sendRealTimeMsg_);
            }
            if (resendNaviGlobalRoute_ != false) {
                output.writeBool(9, resendNaviGlobalRoute_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (modState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.MOD_OFF.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, modState_);
            }
            if (modMappingState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.MOD_MAPPER_OFF.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, modMappingState_);
            }
            if (nohdState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.NOHD_OFF.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, nohdState_);
            }
            if (nocdState_ != com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.NOCD_OFF.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(4, nocdState_);
            }
            if (modRecommendMapId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, modRecommendMapId_);
            }
            if (modUserSelectMapId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, modUserSelectMapId_);
            }
            if (modMapperMapId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(7, modMapperMapId_);
            }
            if (sendRealTimeMsg_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(8, sendRealTimeMsg_);
            }
            if (resendNaviGlobalRoute_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(9, resendNaviGlobalRoute_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo)) {
                return super.equals(obj);
            }
            com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo other = (com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo) obj;

            if (modState_ != other.modState_) return false;
            if (modMappingState_ != other.modMappingState_) return false;
            if (nohdState_ != other.nohdState_) return false;
            if (nocdState_ != other.nocdState_) return false;
            if (getModRecommendMapId()
                    != other.getModRecommendMapId()) return false;
            if (getModUserSelectMapId()
                    != other.getModUserSelectMapId()) return false;
            if (getModMapperMapId()
                    != other.getModMapperMapId()) return false;
            if (getSendRealTimeMsg()
                    != other.getSendRealTimeMsg()) return false;
            if (getResendNaviGlobalRoute()
                    != other.getResendNaviGlobalRoute()) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MOD_STATE_FIELD_NUMBER;
            hash = (53 * hash) + modState_;
            hash = (37 * hash) + MOD_MAPPING_STATE_FIELD_NUMBER;
            hash = (53 * hash) + modMappingState_;
            hash = (37 * hash) + NOHD_STATE_FIELD_NUMBER;
            hash = (53 * hash) + nohdState_;
            hash = (37 * hash) + NOCD_STATE_FIELD_NUMBER;
            hash = (53 * hash) + nocdState_;
            hash = (37 * hash) + MOD_RECOMMEND_MAP_ID_FIELD_NUMBER;
            hash = (53 * hash) + getModRecommendMapId();
            hash = (37 * hash) + MOD_USER_SELECT_MAP_ID_FIELD_NUMBER;
            hash = (53 * hash) + getModUserSelectMapId();
            hash = (37 * hash) + MOD_MAPPER_MAP_ID_FIELD_NUMBER;
            hash = (53 * hash) + getModMapperMapId();
            hash = (37 * hash) + SEND_REAL_TIME_MSG_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getSendRealTimeMsg());
            hash = (37 * hash) + RESEND_NAVI_GLOBAL_ROUTE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getResendNaviGlobalRoute());
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * *
         * 概述：域控行车（MOD/NOHD）应用信息（域控提供给导航App）
         * 类型：Push
         * Sender_ID:
         * RSP_Type:
         * Msg_Set:
         * Msg_ID：
         * Direction：cECU --&gt; App（OEM导航App）
         * </pre>
         * <p>
         * Protobuf type {@code com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo)
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo.class, com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo.Builder.class);
            }

            // Construct using com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo.newBuilder()
            private Builder() {

            }

            private Builder(
                    BuilderParent parent) {
                super(parent);

            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                modState_ = 0;
                modMappingState_ = 0;
                nohdState_ = 0;
                nocdState_ = 0;
                modRecommendMapId_ = 0;
                modUserSelectMapId_ = 0;
                modMapperMapId_ = 0;
                sendRealTimeMsg_ = false;
                resendNaviGlobalRoute_ = false;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor;
            }

            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo build() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo buildPartial() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo result = new com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.modState_ = modState_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.modMappingState_ = modMappingState_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.nohdState_ = nohdState_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.nocdState_ = nocdState_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.modRecommendMapId_ = modRecommendMapId_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.modUserSelectMapId_ = modUserSelectMapId_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.modMapperMapId_ = modMapperMapId_;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    result.sendRealTimeMsg_ = sendRealTimeMsg_;
                }
                if (((from_bitField0_ & 0x00000100) != 0)) {
                    result.resendNaviGlobalRoute_ = resendNaviGlobalRoute_;
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo) {
                    return mergeFrom((com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo other) {
                if (other == getDefaultInstance()) return this;
                if (other.modState_ != 0) {
                    setModStateValue(other.getModStateValue());
                }
                if (other.modMappingState_ != 0) {
                    setModMappingStateValue(other.getModMappingStateValue());
                }
                if (other.nohdState_ != 0) {
                    setNohdStateValue(other.getNohdStateValue());
                }
                if (other.nocdState_ != 0) {
                    setNocdStateValue(other.getNocdStateValue());
                }
                if (other.getModRecommendMapId() != 0) {
                    setModRecommendMapId(other.getModRecommendMapId());
                }
                if (other.getModUserSelectMapId() != 0) {
                    setModUserSelectMapId(other.getModUserSelectMapId());
                }
                if (other.getModMapperMapId() != 0) {
                    setModMapperMapId(other.getModMapperMapId());
                }
                if (other.getSendRealTimeMsg() != false) {
                    setSendRealTimeMsg(other.getSendRealTimeMsg());
                }
                if (other.getResendNaviGlobalRoute() != false) {
                    setResendNaviGlobalRoute(other.getResendNaviGlobalRoute());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                modState_ = input.readEnum();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 16: {
                                modMappingState_ = input.readEnum();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 24: {
                                nohdState_ = input.readEnum();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 32: {
                                nocdState_ = input.readEnum();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 40: {
                                modRecommendMapId_ = input.readUInt32();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 40
                            case 48: {
                                modUserSelectMapId_ = input.readUInt32();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 48
                            case 56: {
                                modMapperMapId_ = input.readUInt32();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 56
                            case 64: {
                                sendRealTimeMsg_ = input.readBool();
                                bitField0_ |= 0x00000080;
                                break;
                            } // case 64
                            case 72: {
                                resendNaviGlobalRoute_ = input.readBool();
                                bitField0_ |= 0x00000100;
                                break;
                            } // case 72
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private int modState_ = 0;

            /**
             * <pre>
             * MOD行车状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
             *
             * @return The enum numeric value on the wire for modState.
             */
            @Override
            public int getModStateValue() {
                return modState_;
            }

            /**
             * <pre>
             * MOD行车状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
             *
             * @param value The enum numeric value on the wire for modState to set.
             * @return This builder for chaining.
             */
            public Builder setModStateValue(int value) {
                modState_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * MOD行车状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
             *
             * @return The modState.
             */
            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState getModState() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.forNumber(modState_);
                return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * MOD行车状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
             *
             * @param value The modState to set.
             * @return This builder for chaining.
             */
            public Builder setModState(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModState value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                modState_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * MOD行车状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModState mod_state = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModState() {
                bitField0_ = (bitField0_ & ~0x00000001);
                modState_ = 0;
                onChanged();
                return this;
            }

            private int modMappingState_ = 0;

            /**
             * <pre>
             * MOD建图状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
             *
             * @return The enum numeric value on the wire for modMappingState.
             */
            @Override
            public int getModMappingStateValue() {
                return modMappingState_;
            }

            /**
             * <pre>
             * MOD建图状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
             *
             * @param value The enum numeric value on the wire for modMappingState to set.
             * @return This builder for chaining.
             */
            public Builder setModMappingStateValue(int value) {
                modMappingState_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * MOD建图状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
             *
             * @return The modMappingState.
             */
            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState getModMappingState() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.forNumber(modMappingState_);
                return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * MOD建图状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
             *
             * @param value The modMappingState to set.
             * @return This builder for chaining.
             */
            public Builder setModMappingState(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumModMapperState value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                modMappingState_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * MOD建图状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumModMapperState mod_mapping_state = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModMappingState() {
                bitField0_ = (bitField0_ & ~0x00000002);
                modMappingState_ = 0;
                onChanged();
                return this;
            }

            private int nohdState_ = 0;

            /**
             * <pre>
             * NOHD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
             *
             * @return The enum numeric value on the wire for nohdState.
             */
            @Override
            public int getNohdStateValue() {
                return nohdState_;
            }

            /**
             * <pre>
             * NOHD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
             *
             * @param value The enum numeric value on the wire for nohdState to set.
             * @return This builder for chaining.
             */
            public Builder setNohdStateValue(int value) {
                nohdState_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * NOHD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
             *
             * @return The nohdState.
             */
            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState getNohdState() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.forNumber(nohdState_);
                return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * NOHD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
             *
             * @param value The nohdState to set.
             * @return This builder for chaining.
             */
            public Builder setNohdState(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNohdState value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                nohdState_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * NOHD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNohdState nohd_state = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearNohdState() {
                bitField0_ = (bitField0_ & ~0x00000004);
                nohdState_ = 0;
                onChanged();
                return this;
            }

            private int nocdState_ = 0;

            /**
             * <pre>
             * NOCD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
             *
             * @return The enum numeric value on the wire for nocdState.
             */
            @Override
            public int getNocdStateValue() {
                return nocdState_;
            }

            /**
             * <pre>
             * NOCD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
             *
             * @param value The enum numeric value on the wire for nocdState to set.
             * @return This builder for chaining.
             */
            public Builder setNocdStateValue(int value) {
                nocdState_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * NOCD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
             *
             * @return The nocdState.
             */
            @Override
            public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState getNocdState() {
                com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState result = com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.forNumber(nocdState_);
                return result == null ? com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * NOCD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
             *
             * @param value The nocdState to set.
             * @return This builder for chaining.
             */
            public Builder setNocdState(com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.EnumNocdState value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                nocdState_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * NOCD状态机
             * </pre>
             *
             * <code>.com.desaysv.psmap.model.bean.EnumNocdState nocd_state = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearNocdState() {
                bitField0_ = (bitField0_ & ~0x00000008);
                nocdState_ = 0;
                onChanged();
                return this;
            }

            private int modRecommendMapId_;

            /**
             * <pre>
             * 自推荐地图id
             * </pre>
             *
             * <code>uint32 mod_recommend_map_id = 5;</code>
             *
             * @return The modRecommendMapId.
             */
            @Override
            public int getModRecommendMapId() {
                return modRecommendMapId_;
            }

            /**
             * <pre>
             * 自推荐地图id
             * </pre>
             *
             * <code>uint32 mod_recommend_map_id = 5;</code>
             *
             * @param value The modRecommendMapId to set.
             * @return This builder for chaining.
             */
            public Builder setModRecommendMapId(int value) {

                modRecommendMapId_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 自推荐地图id
             * </pre>
             *
             * <code>uint32 mod_recommend_map_id = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModRecommendMapId() {
                bitField0_ = (bitField0_ & ~0x00000010);
                modRecommendMapId_ = 0;
                onChanged();
                return this;
            }

            private int modUserSelectMapId_;

            /**
             * <pre>
             * 用户选择地图id
             * </pre>
             *
             * <code>uint32 mod_user_select_map_id = 6;</code>
             *
             * @return The modUserSelectMapId.
             */
            @Override
            public int getModUserSelectMapId() {
                return modUserSelectMapId_;
            }

            /**
             * <pre>
             * 用户选择地图id
             * </pre>
             *
             * <code>uint32 mod_user_select_map_id = 6;</code>
             *
             * @param value The modUserSelectMapId to set.
             * @return This builder for chaining.
             */
            public Builder setModUserSelectMapId(int value) {

                modUserSelectMapId_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 用户选择地图id
             * </pre>
             *
             * <code>uint32 mod_user_select_map_id = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModUserSelectMapId() {
                bitField0_ = (bitField0_ & ~0x00000020);
                modUserSelectMapId_ = 0;
                onChanged();
                return this;
            }

            private int modMapperMapId_;

            /**
             * <pre>
             * 建图完成地图id
             * </pre>
             *
             * <code>uint32 mod_mapper_map_id = 7;</code>
             *
             * @return The modMapperMapId.
             */
            @Override
            public int getModMapperMapId() {
                return modMapperMapId_;
            }

            /**
             * <pre>
             * 建图完成地图id
             * </pre>
             *
             * <code>uint32 mod_mapper_map_id = 7;</code>
             *
             * @param value The modMapperMapId to set.
             * @return This builder for chaining.
             */
            public Builder setModMapperMapId(int value) {

                modMapperMapId_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 建图完成地图id
             * </pre>
             *
             * <code>uint32 mod_mapper_map_id = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModMapperMapId() {
                bitField0_ = (bitField0_ & ~0x00000040);
                modMapperMapId_ = 0;
                onChanged();
                return this;
            }

            private boolean sendRealTimeMsg_;

            /**
             * <pre>
             * 开始/结束发送导航实时数据
             * </pre>
             *
             * <code>bool send_real_time_msg = 8;</code>
             *
             * @return The sendRealTimeMsg.
             */
            @Override
            public boolean getSendRealTimeMsg() {
                return sendRealTimeMsg_;
            }

            /**
             * <pre>
             * 开始/结束发送导航实时数据
             * </pre>
             *
             * <code>bool send_real_time_msg = 8;</code>
             *
             * @param value The sendRealTimeMsg to set.
             * @return This builder for chaining.
             */
            public Builder setSendRealTimeMsg(boolean value) {

                sendRealTimeMsg_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 开始/结束发送导航实时数据
             * </pre>
             *
             * <code>bool send_real_time_msg = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSendRealTimeMsg() {
                bitField0_ = (bitField0_ & ~0x00000080);
                sendRealTimeMsg_ = false;
                onChanged();
                return this;
            }

            private boolean resendNaviGlobalRoute_;

            /**
             * <pre>
             * 重新发送导航规划路径
             * </pre>
             *
             * <code>bool resend_navi_global_route = 9;</code>
             *
             * @return The resendNaviGlobalRoute.
             */
            @Override
            public boolean getResendNaviGlobalRoute() {
                return resendNaviGlobalRoute_;
            }

            /**
             * <pre>
             * 重新发送导航规划路径
             * </pre>
             *
             * <code>bool resend_navi_global_route = 9;</code>
             *
             * @param value The resendNaviGlobalRoute to set.
             * @return This builder for chaining.
             */
            public Builder setResendNaviGlobalRoute(boolean value) {

                resendNaviGlobalRoute_ = value;
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 重新发送导航规划路径
             * </pre>
             *
             * <code>bool resend_navi_global_route = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearResendNaviGlobalRoute() {
                bitField0_ = (bitField0_ & ~0x00000100);
                resendNaviGlobalRoute_ = false;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo)
        }

        // @@protoc_insertion_point(class_scope:com.desaysv.psmap.model.bean.CECUPushDrivingAppInfo)
        private static final com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo();
        }

        public static com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<CECUPushDrivingAppInfo>
                PARSER = new com.google.protobuf.AbstractParser<CECUPushDrivingAppInfo>() {
            @Override
            public CECUPushDrivingAppInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<CECUPushDrivingAppInfo> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<CECUPushDrivingAppInfo> getParserForType() {
            return PARSER;
        }

        @Override
        public com.desaysv.psmap.model.bean.CecuPushDrivingAppInfo.CECUPushDrivingAppInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n cecu_push_driving_app_info.proto\022\034com." +
                        "desaysv.psmap.model.bean\"\275\003\n\026CECUPushDri" +
                        "vingAppInfo\022=\n\tmod_state\030\001 \001(\0162*.com.des" +
                        "aysv.psmap.model.bean.EnumModState\022K\n\021mo" +
                        "d_mapping_state\030\002 \001(\01620.com.desaysv.psma" +
                        "p.model.bean.EnumModMapperState\022?\n\nnohd_" +
                        "state\030\003 \001(\0162+.com.desaysv.psmap.model.be" +
                        "an.EnumNohdState\022?\n\nnocd_state\030\004 \001(\0162+.c" +
                        "om.desaysv.psmap.model.bean.EnumNocdStat" +
                        "e\022\034\n\024mod_recommend_map_id\030\005 \001(\r\022\036\n\026mod_u" +
                        "ser_select_map_id\030\006 \001(\r\022\031\n\021mod_mapper_ma" +
                        "p_id\030\007 \001(\r\022\032\n\022send_real_time_msg\030\010 \001(\010\022 " +
                        "\n\030resend_navi_global_route\030\t \001(\010*\327\001\n\014Enu" +
                        "mModState\022\013\n\007MOD_OFF\020\000\022\021\n\rMOD_NOT_READY\020" +
                        "\001\022\r\n\tMOD_READY\020\002\022\020\n\014MOD_LOCATION\020\003\022\017\n\013MO" +
                        "D_STANDBY\020\004\022\014\n\010MOD_WAIT\020\005\022\016\n\nMOD_ACTIVE\020" +
                        "\006\022\022\n\016MOD_BGLOCATION\020\007\022\021\n\rMOD_BGSTANDBY\020\010" +
                        "\022\016\n\nMOD_BGWAIT\020\t\022\021\n\rMOD_D130_WAIT\020\n\022\r\n\tM" +
                        "OD_ERROR\020\013*\275\001\n\022EnumModMapperState\022\022\n\016MOD" +
                        "_MAPPER_OFF\020\000\022\030\n\024MOD_MAPPER_NOT_READY\020\001\022" +
                        "\024\n\020MOD_MAPPER_READY\020\002\022\033\n\027MOD_MAPPER_MAP_" +
                        "TRAINING\020\003\022\031\n\025MOD_MAPPER_MAP_SAVING\020\004\022\025\n" +
                        "\021MOD_MAPPER_FINISH\020\005\022\024\n\020MOD_MAPPER_ERROR" +
                        "\020\006*`\n\rEnumNohdState\022\014\n\010NOHD_OFF\020\000\022\020\n\014NOH" +
                        "D_STANDBY\020\001\022\016\n\nNOHD_READY\020\002\022\017\n\013NOHD_ACTI" +
                        "VE\020\003\022\016\n\nNOHD_ERROR\020\004*`\n\rEnumNocdState\022\014\n" +
                        "\010NOCD_OFF\020\000\022\020\n\014NOCD_STANDBY\020\001\022\016\n\nNOCD_RE" +
                        "ADY\020\002\022\017\n\013NOCD_ACTIVE\020\003\022\016\n\nNOCD_ERROR\020\004b\006" +
                        "proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_com_desaysv_psmap_model_bean_CECUPushDrivingAppInfo_descriptor,
                new String[]{"ModState", "ModMappingState", "NohdState", "NocdState", "ModRecommendMapId", "ModUserSelectMapId", "ModMapperMapId", "SendRealTimeMsg", "ResendNaviGlobalRoute",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
