package com.desaysv.psmap.adapter.standard

object ProtocolID {

    const val PROTOCOL_GET_VERSION: Int = 99999

    const val PROTOCOL_MAP_OPERA: Int = 30000

    const val PROTOCOL_BACK_TO_MAP: Int = 30001

    const val PROTOCOL_SHOW_MY_LOCATION: Int = 30002

    const val PROTOCOL_GET_TRAFFIC_INFO: Int = 30003

    const val PROTOCOL_GET_ROUTE_INFO: Int = 30005

    const val PROTOCOL_REGISTER_ACTIVEDIALOGUE: Int = 30009

    const val PROTOCOL_REQUEST_AUTO_THEME: Int = 30014

    const val PROTOCOL_SWITCH_AUTO_THEME: Int = 30015

    const val PROTOCOL_KEYWORD_SEARCH: Int = 30300

    const val PROTOCOL_AROUNDSEARCH_SEARCH: Int = 30301

    const val PROTOCOL_ALONG_THE_WAY_SEARCH: Int = 30302

    const val PROTOCOL_DISTRICT_SEARCH: Int = 30303

    const val PROTOCOL_HOME_COMPANY_AROUNDSEARCH_SEARCH: Int = 30304

    const val PROTOCOL_SEARCH_HISTORY_DESTINATION: Int = 30305

    const val PROTOCOL_FREQUENT_POIS: Int = 30013

    const val PROTOCOL_SPECIAL_POI_NAVI: Int = 30400

    const val PROTOCOL_SET_SPECIAL_POI: Int = 30401

    const val PROTOCOL_REQUEST_ROUTE_EX: Int = 30402

    const val PROTOCOL_ROUTE_SELECT: Int = 30404

    const val PROTOCOL_MODIFY_NAVI_VIA: Int = 30409

    const val PROTOCOL_NAVI_OPERA: Int = 30406

    const val PROTOCOL_ON_NAVI_ROUTE_PREFER: Int = 30405

    const val PROTOCOL_GUIDE_INFO: Int = 30407

    const val PROTOCOL_FRONT_TRAFFIC_RADIO: Int = 30408

    const val PROTOCOL_HIGHWAY_EXIT: Int = 30410

    const val PROTOCOL_SHARE_TRIP_BY_TEL_NUM: Int = 30411

    const val PROTOCOL_DRIVE_GAS_OIL: Int = 30412

    const val PROTOCOL_PARK_RECOMMEND: Int = 30416

    const val PROTOCOL_PARK_OPERA: Int = 30417

    const val PROTOCOL_AVOID_JAM: Int = 30418

    const val PROTOCOL_AVOID_JAM_OPERA: Int = 30419

    const val PROTOCOL_OIL_REMIND_OPERA: Int = 30420

    const val PROTOCOL_CONTINUE_NAVI: Int = 30422

    const val PROTOCOL_CONTINUE_NAVI_OPERA: Int = 30423

    const val PROTOCOL_GET_TRAFFIC_LANE_INFO: Int = 30424

    const val PROTOCOL_GET_SAFED_DRIVING: Int = 30425

    const val PROTOCOL_SEND_MANEUVERICON: Int = 30426

    const val PROTOCOL_TRIP_REPORTER: Int = 30430

    const val PROTOCOL_NOTIFY_TSR_INFO: Int = 30413

    const val PROTOCOL_SWITCH_AVOID_LIMIT: Int = 30427

    const val PROTOCOL_SET_WIPE_STATE: Int = 30431

    const val PROTOCOL_SET_NAVI_TYPE: Int = 30432

    const val PROTOCOL_AUTO_STATUS: Int = 30200

    const val PROTOCOL_ACTIVE_REQUEST_BING: Int = 30500

    const val PROTOCOL_ACTIVE_RESPONSE_BIND: Int = 30501

    const val PROTOCOL_INACTIVE_CONFIRM_NEED_BING: Int = 30502

    const val PROTOCOL_INACTIVE_RESPONSE_BIND: Int = 30503

    const val PROTOCOL_LOGOUT: Int = 30504

    const val PROTOCOL_RESPONSE_LOGOUT: Int = 30505

    const val PROTOCOL_Union_Login: Int = 30506

    const val PROTOCOL_GET_FAVORITE_POI: Int = 30507

    const val PROTOCOL_HOME_COMPANY_FAVORITE_CHANGE_NOTY: Int = 30508

    const val PROTOCOL_FAVORITE_ANY_POI: Int = 30509

    const val PROTOCOL_FAVORITE_CURRENT_POI: Int = 30004

    const val PROTOCOL_SET_MUTE: Int = 30006

    const val PROTOCOL_GET_MUTE_STATE: Int = 30008

    const val PROTOCOL_REQUEST_SILENT_AUTO_LOGIN: Int = 30515

    const val PROTOCOL_Request_Oil_Volume: Int = 30600

    const val PROTOCOL_Response_Oil_Volume: Int = 30601

    const val PROTOCOL_Request_Power_Status: Int = 30602

    const val PROTOCOL_Response_Power_Status: Int = 30603

    const val PROTOCOL_REQUEST_CARHW_STATUS: Int = 30606

    const val PROTOCOL_RESPONSE_CARHW_STATUS: Int = 30607

    const val PROTOCOL_Response_Home_company_tmc: Int = 30007

    const val PROTOCOL_CRUISE_PLAY_TYPE: Int = 30016

    const val PROTOCOL_START_UNION_LOGIN: Int = 30511

    const val PROTOCOL_START_LOGIN: Int = 30510

    const val PROTOCOL_GET_VEHICLE: Int = 30604

    const val PROTOCOL_REQUEST_CAR_VEHICLE: Int = 30605

    const val PROTOCOL_GOTO_HOME_COMPANY: Int = 30010

    const val PROTOCOL_LOC_NMEA_INFO: Int = 30201

    const val PROTOCOL_LOC_WGS_TO_GCJ_INFO: Int = 30202

    const val PROTOCOL_LOC_GET_MMF_INFO: Int = 30203

    const val PROTOCOL_LOC_LOCATION_REPORT: Int = 30204

    const val PROTOCOL_LOGIN_AUTOMOBILE: Int = 30512

    const val PROTOCOL_REPORT_NAVI_MODEL: Int = 30011

    const val PROTOCOL_VIEW_POI: Int = 30012

    const val PROTOCOL_PAGE_JUMP_OPERATE: Int = 30306

    const val PROTOCOL_OPERATE_EXTSCREEN: Int = 30800

    const val PROTOCOL_NOTIFY_EXTSCREEN_STATUS: Int = 30801

    const val PROTOCOL_REQUEST_SYSTEM_FONT: Int = 30900

    const val PROTOCOL_SET_SYSTEM_FONT: Int = 30901

    const val PROTOCOL_CAMERA_STATUS_REQUEST_TYPE: Int = 30433

    const val PROTOCOL_CAMERA_STATUS_NOTIFY_TYPE: Int = 30434

    const val PROTOCOL_TMC_SEGMENT_TYPE: Int = 30435

    const val PROTOCOL_TMC_SEGMENT_DISPATCH_CONTROL: Int = 30436

    const val PROTOCOL_NOTIFY_AR_STATUS: Int = 30437

    const val PROTOCOL_NOTIFY_AR_SHOW: Int = 30438

    const val PROTOCOL_TURNON_BLUETOOTH: Int = 80001

    const val PROTOCOL_IS_BLUETOOTH_ENABLED: Int = 80003

    const val PROTOCOL_TRIP_GETNAVIACTIVETYPE: Int = 80005

    const val PROTOCOL_OTHER_FUNCCONFIGLOADINGSTATUS: Int = 80154

    const val PROTOCOL_INFO_NOTIFY_MAPSTATEINFOQUERY: Int = 80008

    const val PROTOCOL_CAR_ISARNAVIENABLE: Int = 80010

    const val PROTOCOL_CAR_ISARNAVIENABLENOTIFY: Int = 80011

    const val PROTOCOL_OTHER_VOLUMENOTIFYTOAUTO: Int = 80013

    const val PROTOCOL_INFO_NOTIFY_VOLUMENOTIFYTOSYSTEM: Int = 80014

    const val PROTOCOL_INFO_NOTIFY_VOLUMEINFOQUERY: Int = 80015

    const val PROTOCOL_INFO_NOTIFY_VOLUMEINFO_TO_AUTO: Int = 80016

    const val PROTOCOL_TRIP_ARCAMERAID: Int = 80021

    const val PROTOCOL_MAP_MAPMOVEOFEIGHTDIRECTION: Int = 80048

    const val PROTOCOL_OTHER_SETTINGDAYNIGHTMODE: Int = 80024

    const val PROTOCOL_INFO_NOTIFY_QUERYDAYNIGHTMODE: Int = 80025

    const val PROTOCOL_INFO_NOTIFY_QUERYLASTMAPSTATUS: Int = 80026

    const val PROTOCOL_INFO_NOTIFY_DATACONSUMPTIONINFO: Int = 80049

    const val PROTOCOL_TRIP_RESIDUALENERGYINFO: Int = 80050

    const val PROTOCOL_OTHER_GETAREAINFO: Int = 80030

    const val PROTOCOL_INFO_NOTIFY_GPSSTATUSNOTIFY: Int = 80033

    const val PROTOCOL_USER_OPENSAVES: Int = 80047

    const val PROTOCOL_CAR_CARENERGYINFO: Int = 80038

    const val PROTOCOL_CAR_CARCHARGESTATENOTIFY: Int = 80037

    const val PROTOCOL_CAR_ADDITIONALENERGYNOTIFY: Int = 80035

    const val PROTOCOL_CAR_DRIVINGMODECHANGENOTIFY: Int = 80036

    const val PROTOCOL_OTHER_RESTOREDEFAULTSETTINGS: Int = 80043

    const val PROTOCOL_OTHER_CLEARHISTORYOPERATIONRECORD: Int = 80042

    const val PROTOCOL_TRIP_FLEETIMOPERATION: Int = 80051

    const val PROTOCOL_OTHER_MULTISCREENSTATUS: Int = 80028

    const val PROTOCOL_CAR_NOTIFYVEHICLESTATE: Int = 80040

    const val PROTOCOL_CAR_GETVEHICLESTATE: Int = 80041

    const val PROTOCOL_OTHER_RETURNSTATESOFCLEARHISTORYRECORD: Int = 80052

    const val PROTOCOL_OTHER_SYSTEMDAYNIGHTMODE: Int = 80056

    const val PROTOCOL_INFO_NOTIFY_CURRENTROADNAMEDISPATCH: Int = 80057

    const val PROTOCOL_INFO_NOTIFY_CONTROLCOMMUTETIPSHOWORNOT: Int = 80059

    const val PROTOCOL_INFO_NOTIFY_CONTROLCONTINUENAVITIPSHOWORNOT: Int = 80060

    const val PROTOCOL_OTHER_SOFTWAREINFOQUERY: Int = 80079

    const val PROTOCOL_INFO_NOTIFY_SOFTWAREINFONOTIFY: Int = 80070

    const val PROTOCOL_TRIP_ENDNAVIGATION: Int = 80078

    const val PROTOCOL_SEARCH_SENDSEARCHRESULTLISTSTATE: Int = 80034

    const val PROTOCOL_OTHER_HEADINGDIRECTION: Int = 80063

    const val PROTOCOL_SEARCH_SEARCHRESULTOPERATE: Int = 80023

    const val PROTOCOL_CAR_ACCONNOTIFY: Int = 80088

    const val PROTOCOL_OTHER_SENDDESINFOLASTMILE: Int = 80068

    const val PROTOCOL_MAP_EXITAUTO: Int = 80045

    const val PROTOCOL_OTHER_ACTIVATESTATUS: Int = 80067

    const val PROTOCOL_OTHER_SCREENSHOTPATH: Int = 80071

    const val PROTOCOL_OTHER_TTSTEXTFORAUTO: Int = 80082

    const val PROTOCOL_TRIP_REPEATBROADCAST: Int = 80083

    const val PROTOCOL_OTHER_VOICEASSISTANTCONTROL: Int = 80087

    const val PROTOCOL_CAR_SPEEDLIMITSWITCHSTATENOTIFY: Int = 80075

    const val PROTOCOL_MAP_MINIMIZEAUTO: Int = 80046

    const val PROTOCOL_OTHER_SETTINGBROADCASTROLES: Int = 80085

    const val PROTOCOL_OTHER_SCALESTATUSNOTIFY: Int = 80064

    const val PROTOCOL_OTHER_TRAFFICEVENTSREPORT: Int = 80069

    const val PROTOCOL_MAP_MOVEMAP: Int = 80090

    const val PROTOCOL_TRIP_PHOTO: Int = 80084

    const val PROTOCOL_MAP_ENTERAUTO: Int = 80044

    const val PROTOCOL_OTHER_NOTICEOPERATE: Int = 80081

    const val PROTOCOL_TRIP_HUDNAVIGATION: Int = 80074

    const val PROTOCOL_TRIP_FATIGUEDRIVINGBROADCAST: Int = 80073

    const val PROTOCOL_OTHER_QUERYSAVES: Int = 80072

    const val PROTOCOL_INFO_NOTIFY_SEND2CARINFO: Int = 80089

    const val PROTOCOL_TRIP_ROUTEOVERVIEW: Int = 80076

    const val PROTOCOL_TRIP_WHETHERBACKOVERVIEWSTATUS: Int = 80077

    const val PROTOCOL_INFO_NOTIFY_MAPOPERATERESULT: Int = 80095

    const val PROTOCOL_INFO_NOTIFY_TRAFFICRESTRICTQUERY: Int = 80097

    const val PROTOCOL_OTHER_SCALELEVELNOTIFY: Int = 80100

    const val PROTOCOL_INFO_NOTIFY_GUIDEINFOOUTPUT: Int = 80099

    const val PROTOCOL_OTHER_FINGERSSLIDINGOPERATIONNOTIFY: Int = 80103

    const val PROTOCOL_OTHER_SETEXPANSIONSCREENJVSWITCH: Int = 80101

    const val PROTOCOL_OTHER_EXTERNALSCREENACTION: Int = 80110

    const val PROTOCOL_OTHER_SETEXPANSIONSCREENMAPPARM: Int = 80111

    const val PROTOCOL_TRIP_MIDPOISINFONOTIFY: Int = 80108

    const val PROTOCOL_INFO_NOTIFY_CAMERASPEEDINFO: Int = 80105

    const val PROTOCOL_INFO_NOTIFY_AVOIDJAMOPERATESTATUS: Int = 80119

    const val PROTOCOL_OTHER_SETEXPANSIONSCREENTYPE: Int = 80102

    const val PROTOCOL_INFO_NOTIFY_MESSAGEDISAPPEARNOTIFY: Int = 80116

    const val PROTOCOL_MAP_POIINFOSHARE: Int = 80109

    const val PROTOCOL_OTHER_QUERYBACKSTAGECURISESWITCHSTATE: Int = 80114

    const val PROTOCOL_INFO_NOTIFY_PLAYSETTINGSTATUSDISPATCH: Int = 80122

    const val PROTOCOL_TRIP_SWITCHMAINANDAUXILIARYROAD: Int = 80107

    const val PROTOCOL_CAR_CARPLATEINFO: Int = 80104

    const val PROTOCOL_OTHER_SLOPEANDROLLANGLEINFO: Int = 80112

    const val PROTOCOL_INFO_NOTIFY_COORDINATETRANSFORMINFO: Int = 80113

    const val PROTOCOL_OTHER_NETWORKPOSITIONSWITCH: Int = 80115

    const val PROTOCOL_OTHER_AROPERATIONINFORM: Int = 80120

    const val PROTOCOL_OTHER_ARNAVIGATIONLDWINFO: Int = 80123

    const val PROTOCOL_TRIP_CHOOSEHOMEANDCOMPANYINFO: Int = 80127

    const val PROTOCOL_TRIP_ISNOAFUNCTIONOPEN: Int = 80124

    const val PROTOCOL_INFO_NOTIFY_COMMUTINGSTATUS: Int = 80128

    const val PROTOCOL_OTHER_AUTOUPDATEROLLBACK: Int = 80131

    const val PROTOCOL_MAP_BRINGAUTOTOFOREGROUND: Int = 80132

    const val PROTOCOL_OTHER_SYSTEMKEYBOARDSTATUSINFORM: Int = 80134

    const val PROTOCOL_OTHER_PATHCONFIGINFO: Int = 80129

    const val PROTOCOL_TRIP_NEWMIDPOISINFONOTIFY: Int = 80138

    const val PROTOCOL_OTHER_NEWQUERYSAVES: Int = 80139

    const val PROTOCOL_INFO_NOTIFY_CHANNELID: Int = 80143

    const val PROTOCOL_CAR_GETMANUFACTUREINFO: Int = 80147

    const val PROTOCOL_CAR_GETMANUFACTUREINFOFROMAUTO: Int = 80148

    const val PROTOCOL_CAR_GETVEHICLEENERGYTYPEFROMAUTO: Int = 80145

    const val PROTOCOL_INFO_NOTIFY_VEHICLEENERGYINFO: Int = 80146

    const val PROTOCOL_CAR_CARRESTRICTIONSINFO: Int = 80142

    const val PROTOCOL_CAR_GETACCOUNTINFO: Int = 80140

    const val PROTOCOL_CAR_GETACCOUNTINFOFROMAUTO: Int = 80141

    const val PROTOCOL_CAR_GETPLATENUMBER: Int = 80149

    const val PROTOCOL_CAR_GETPLATENUMBERFROMAUTO: Int = 80150

    const val PROTOCOL_TRIP_GROUPDESTINATIONCHANGE: Int = 80153

    const val PROTOCOL_TRIP_ROUTEINFOCONTRAST: Int = 80155

    const val PROTOCOL_TRIP_ROUTECHANGE: Int = 80156

    const val PROTOCOL_OTHER_NETWORKSTATUSINFO: Int = 80133

    const val PROTOCOL_MAP_GETMAPOPERATERESULT: Int = 80157

    const val PROTOCOL_OTHER_MAPDOWNLOAD: Int = 80165

    const val PROTOCOL_OTHER_NAVIFUNCTIONCHECK: Int = 80166

    const val PROTOCOL_MAP_GEODECODE: Int = 80160

    const val PROTOCOL_TRIP_GETROUTECONTINUEINFO: Int = 80164

    const val PROTOCOL_OTHER_SETNAVIFUNC: Int = 80168

    const val PROTOCOL_INFO_NOTIFY_SEARCHNAVINFO: Int = 80163

    const val PROTOCOL_SEARCH_HISTORYOUTPUT: Int = 80161

    const val PROTOCOL_ARNAVI_ARHUDROUTEINFOOUTPUT: Int = 80159

    const val PROTOCOL_OTHER_OPENNAVIFUNC: Int = 80175

    const val PROTOCOL_ARNAVI_ARHUDGUIDELINEOUTPUT: Int = 80177

    const val PROTOCOL_ARNAVI_ARHUDTBTINFOOUTPUT: Int = 80176

    const val PROTOCOL_ARNAVI_ARHUDARRIVEPOINTOUTPUT: Int = 80178

    const val PROTOCOL_NAVI_ROUTE_PREFER: Int = 80179

    const val PROTOCOL_QUERY_RESTRICTED_INFO: Int = 80182

    const val PROTOCOL_EHP: Int = 131009

    const val PROTOCOL_FAVORITE_CHANGE_NOTY: Int = 80172


    /*----------------------新增接口----------------------------*/
    //地图返回⻋位视⻆的接⼝
    const val PROTOCOL_BACK_CURRENT_CAR_POSITION: Int = 90000

}